# fly.toml app configuration file generated for linkedin-clone on 2024-01-15T10:30:00Z

app = "linkedin-clone"
primary_region = "sjc"

[build]

[env]
  PORT = "8000"
  HOST = "0.0.0.0"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  grace_period = "5s"
  method = "get"
  path = "/health"
  protocol = "http"
  timeout = "2s"
  tls_skip_verify = false

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512